"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { TbDownload, TbLoader2, TbCheck } from "react-icons/tb";

interface ExportButtonProps {
    plan: any;
}

export function ExportButton({ plan }: ExportButtonProps) {
    const [exporting, setExporting] = useState(false);
    const [exported, setExported] = useState(false);

    const generatePDF = async () => {
        setExporting(true);

        try {
            // Dynamic import to reduce bundle size
            const html2canvas = (await import("html2canvas")).default;
            const jsPDF = (await import("jspdf")).default;

            // Create a temporary div with plan content
            const content = document.createElement("div");
            content.style.cssText = "padding: 40px; background: #0f172a; color: white; width: 800px; font-family: system-ui;";

            const unified = plan?.plan?.unified_plan || plan?.unified_plan || plan || {};

            content.innerHTML = `
                <div style="margin-bottom: 30px;">
                    <h1 style="font-size: 28px; margin-bottom: 10px; color: #818cf8;">WellSync AI</h1>
                    <h2 style="font-size: 20px; color: #94a3b8;">Your Personalized Wellness Plan</h2>
                    <p style="color: #64748b; font-size: 14px;">Generated: ${new Date().toLocaleDateString()}</p>
                </div>

                <div style="margin-bottom: 25px; padding: 20px; background: #1e293b; border-radius: 12px;">
                    <h3 style="color: #60a5fa; margin-bottom: 15px;">💪 Fitness</h3>
                    <p><strong>Focus:</strong> ${unified.fitness?.focus || "Balanced"}</p>
                    <p><strong>Intensity:</strong> ${unified.fitness?.intensity || "Moderate"}</p>
                    <p><strong>Weekly Volume:</strong> ${unified.fitness?.weekly_volume || "120 min"}</p>
                </div>

                <div style="margin-bottom: 25px; padding: 20px; background: #1e293b; border-radius: 12px;">
                    <h3 style="color: #4ade80; margin-bottom: 15px;">🥗 Nutrition</h3>
                    <p><strong>Daily Calories:</strong> ${unified.nutrition?.daily_calories || 2000} kcal</p>
                    <p><strong>Hydration:</strong> ${unified.nutrition?.hydration || "8 glasses"}</p>
                </div>

                <div style="margin-bottom: 25px; padding: 20px; background: #1e293b; border-radius: 12px;">
                    <h3 style="color: #a78bfa; margin-bottom: 15px;">💤 Sleep</h3>
                    <p><strong>Target:</strong> ${unified.sleep?.target_hours || 8} hours</p>
                    <p><strong>Bedtime:</strong> ${unified.sleep?.bedtime || "10:30 PM"}</p>
                    <p><strong>Wake Time:</strong> ${unified.sleep?.wake_time || "6:30 AM"}</p>
                </div>

                <div style="margin-bottom: 25px; padding: 20px; background: #1e293b; border-radius: 12px;">
                    <h3 style="color: #f472b6; margin-bottom: 15px;">🧠 Mental Wellness</h3>
                    <p><strong>Focus:</strong> ${unified.mental_wellness?.focus || "Stress Management"}</p>
                </div>

                <div style="text-align: center; margin-top: 40px; color: #64748b; font-size: 12px;">
                    <p>Generated by WellSync AI - Multi-Agent Wellness System</p>
                </div>
            `;

            document.body.appendChild(content);

            const canvas = await html2canvas(content, {
                backgroundColor: "#0f172a",
                scale: 2,
            });

            document.body.removeChild(content);

            const imgData = canvas.toDataURL("image/png");
            const pdf = new jsPDF({
                orientation: "portrait",
                unit: "px",
                format: [canvas.width / 2, canvas.height / 2],
            });

            pdf.addImage(imgData, "PNG", 0, 0, canvas.width / 2, canvas.height / 2);
            pdf.save("wellsync-wellness-plan.pdf");

            setExported(true);
            setTimeout(() => setExported(false), 3000);
        } catch (error) {
            console.error("Export failed:", error);
        } finally {
            setExporting(false);
        }
    };

    return (
        <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={generatePDF}
            disabled={exporting || !plan}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl font-medium transition-all ${exported
                    ? "bg-green-500/20 text-green-400 border border-green-500/30"
                    : "bg-brand-500/10 text-brand-400 border border-brand-500/30 hover:bg-brand-500/20"
                } disabled:opacity-50`}
        >
            {exporting ? (
                <><TbLoader2 className="w-4 h-4 animate-spin" /> Exporting...</>
            ) : exported ? (
                <><TbCheck className="w-4 h-4" /> Downloaded!</>
            ) : (
                <><TbDownload className="w-4 h-4" /> Export PDF</>
            )}
        </motion.button>
    );
}
