"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { TbShare, TbBrandTwitter, TbBrandWhatsapp, TbLink, TbCheck } from "react-icons/tb";

interface ShareButtonProps {
    plan?: any;
}

export function ShareButton({ plan }: ShareButtonProps) {
    const [showOptions, setShowOptions] = useState(false);
    const [copied, setCopied] = useState(false);

    const getShareText = () => {
        const unified = plan?.plan?.unified_plan || plan?.unified_plan || plan || {};
        return `🌟 Check out my WellSync AI wellness plan!

💪 Fitness: ${unified.fitness?.focus || "Balanced"} training
🥗 Nutrition: ${unified.nutrition?.daily_calories || 2000} kcal/day
💤 Sleep: ${unified.sleep?.target_hours || 8}h target
🧠 Mental: ${unified.mental_wellness?.focus || "Wellness"}

Generated by WellSync AI - Multi-Agent Wellness System
#WellSyncAI #Wellness #AI`;
    };

    const shareToTwitter = () => {
        const text = encodeURIComponent(getShareText());
        window.open(`https://twitter.com/intent/tweet?text=${text}`, "_blank");
    };

    const shareToWhatsApp = () => {
        const text = encodeURIComponent(getShareText());
        window.open(`https://wa.me/?text=${text}`, "_blank");
    };

    const copyLink = async () => {
        const text = getShareText();
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleNativeShare = async () => {
        if (navigator.share) {
            try {
                await navigator.share({
                    title: "My WellSync AI Wellness Plan",
                    text: getShareText(),
                });
            } catch (error) {
                // User cancelled or error
            }
        } else {
            setShowOptions(!showOptions);
        }
    };

    return (
        <div className="relative">
            <motion.button
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
                onClick={handleNativeShare}
                className="flex items-center gap-2 px-4 py-2 bg-green-500/10 text-green-400 border border-green-500/30 rounded-xl hover:bg-green-500/20 transition-all"
            >
                <TbShare className="w-4 h-4" />
                Share Plan
            </motion.button>

            {showOptions && (
                <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="absolute top-full mt-2 right-0 bg-slate-900 border border-slate-800 rounded-xl p-2 shadow-xl z-10 min-w-[160px]"
                >
                    <button
                        onClick={shareToTwitter}
                        className="w-full flex items-center gap-2 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800 rounded-lg transition-colors"
                    >
                        <TbBrandTwitter className="w-4 h-4 text-blue-400" />
                        Twitter
                    </button>
                    <button
                        onClick={shareToWhatsApp}
                        className="w-full flex items-center gap-2 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800 rounded-lg transition-colors"
                    >
                        <TbBrandWhatsapp className="w-4 h-4 text-green-400" />
                        WhatsApp
                    </button>
                    <button
                        onClick={copyLink}
                        className="w-full flex items-center gap-2 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800 rounded-lg transition-colors"
                    >
                        {copied ? (
                            <><TbCheck className="w-4 h-4 text-green-400" /> Copied!</>
                        ) : (
                            <><TbLink className="w-4 h-4" /> Copy Text</>
                        )}
                    </button>
                </motion.div>
            )}
        </div>
    );
}
